name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
          source $HOME/.cargo/env
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build VPK Binary
        run: |
          source $HOME/.cargo/env
          # Aggiorna le dipendenze per essere sicuri di avere l'ultima versione di Ruffle
          cargo +nightly update
          # Compilazione specifica per PS Vita
          cargo +nightly build --target armv7-sony-vita-newlibeabihf --release -Z build-std=std,panic_abort
