name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: rust-src

      - name: Build VPK Binary
        run: |
          # Impostiamo una variabile per dire a Ruffle di non usare funzioni desktop
          export RUSTFLAGS="--cfg ruffle_core='no_precomputed_hashes'"
          
          cargo build \
            -Z build-std=std,panic_abort \
            --target armv7-sony-vita-newlibeabihf.json \
            --release
