name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          # Non aggiungiamo 'targets' qui perch√© lo costruiamo da soli sotto
          components: rust-src

      - name: Build VPK Binary
        run: |
          # Diciamo a Rust di costruirsi da solo i pezzi per la Vita usando i sorgenti (rust-src)
          cargo build \
            -Z build-std=std,panic_abort \
            --target armv7-sony-vita-newlibeabihf.json \
            --release
