name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build VPK Binary
        run: |
          source $HOME/.cargo/env
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          
          # Spieghiamo a Rust dove trovare il compilatore C della Vita
          export VITA_PBP_TOOL=vita-make-fself
          export PKG_CONFIG_ALLOW_CROSS=1
          
          # Compiliamo usando il FILE JSON come target
          cargo +nightly build \
            -Z build-std=std,panic_abort \
            --target armv7-sony-vita-newlibeabihf.json \
            --release
