name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest # Usiamo un contenitore che ha già tutto per la Vita
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          # Nota: PATH verrà aggiornato nel prossimo step

      - name: Build VPK Binary
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup target add armv7-sony-vita-newlibeabihf
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          
          # Rimuoviamo il flag +d16 che dava errore e compiliamo
          export RUSTFLAGS="-C target-feature=+v7,+vfp3,+thumb2"
          cargo +nightly update
          cargo +nightly build --target armv7-sony-vita-newlibeabihf --release -Z build-std=std,panic_abort
