name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # Rimuoviamo il container per ora per evitare conflitti di permessi
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: armv7-sony-vita-newlibeabihf
          components: rust-src

      - name: Build VPK Binary
        run: |
          # Usiamo il comando cargo direttamente, ora DEVE trovarlo
          cargo build \
            -Z build-std=std,panic_abort \
            --target armv7-sony-vita-newlibeabihf.json \
            --release
