name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: |
          # Installazione forzata della versione corretta
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-x86_64-unknown-linux-gnu
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build VPK Binary
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          source $HOME/.cargo/env
          
          # Forziamo l'uso della toolchain corretta eliminando quella sbagliata dal percorso
          rm -rf /github/home/.rustup/toolchains/nightly-x86_64-unknown-linux-musl
          
          # Impostiamo la variabile di ambiente per obbligare Rust a usare GNU
          export RUSTUP_TOOLCHAIN=nightly-x86_64-unknown-linux-gnu
          
          rustup component add rust-src
          
          # Compilazione
          cargo build \
            -Z build-std=std,panic_abort \
            --target armv7-sony-vita-newlibeabihf.json \
            --release
