name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: rust-src

      - name: Install VitaSDK & Libraries
        run: |
          export VITASDK=/opt/vitasdk
          sudo mkdir -p $VITASDK
          sudo chown $USER $VITASDK
          DOWNLOAD_LINK=$(curl -sL https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python3 - master linux)
          curl -L "$DOWNLOAD_LINK" | tar xj -C $VITASDK --strip-components=1
          
          echo "VITASDK=$VITASDK" >> $GITHUB_ENV
          echo "$VITASDK/bin" >> $GITHUB_PATH
          
          # Installiamo le librerie C necessarie (newlib)
          mkdir -p $VITASDK/bin
          curl -L https://raw.githubusercontent.com/vitasdk/vdpm/master/vdpm -o $VITASDK/bin/vdpm
          chmod +x $VITASDK/bin/vdpm
          $VITASDK/bin/vdpm newlib

      - name: Build VPK Binary
        run: |
          # Aggiungiamo i link alle librerie della Vita (-lvitaLinker)
          # Questi flag dicono a Rust dove trovare memset, exit e le funzioni Vita
          export RUSTFLAGS="-L /opt/vitasdk/arm-vita-eabi/lib -lSceKernel_stub -lSceLibc_stub"
          
          cargo build \
            -Z build-std=std,panic_abort \
            --target armv7-sony-vita-newlibeabihf.json \
            --release
