name: Build PS Vita VPK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: rust-src

      # Questa Action scarica il SDK da una cache sicura, non fallir√† il download
      - name: Setup VitaSDK
        uses: G33X-Vita/setup-vitasdk@v2
        with:
          vitasdk-revision: 'master'

      - name: Build Ruffle
        run: |
          # Usiamo le variabili impostate dall'Action
          export RUSTFLAGS="-L $VITASDK/arm-vita-eabi/lib -lSceKernel_stub -lSceLibc_stub -lSceNet_stub"
          
          cargo build \
            -Z build-std=std,panic_abort \
            --target armv7-sony-vita-newlibeabihf.json \
            --release
